from pathlib import Path

from core.analyzer import ProjectProfile
from core.config import OutputConfig

HEADER = "# Auto-generated by ai-context-generator — do not edit directly.\n# See AGENTS.md for the master project governance guidelines.\n"
SIGNATURE = "Auto-generated by ai-context-generator"

POINTER = (
    "This file is auto-generated and lightweight.\n"
    "Read AGENTS.md (in the repository root) for the full project governance guidelines.\n"
    "When AGENTS.md changes, re-run ai-context-generator to refresh this file.\n"
)


class BridgeWriter:
    """Generates lightweight pointer files so every AI tool reads from the same AGENTS.md."""

    def __init__(self, workspace_path: Path, config: OutputConfig, profile: ProjectProfile):
        self.workspace_path = workspace_path
        self.config = config
        self.profile = profile

    def write_all(self) -> list[str]:
        written: list[str] = []

        # --- Cursor IDE ---
        if self.config.cursorrules and self._write(".cursorrules", HEADER + POINTER):
            written.append(".cursorrules")

        # --- Windsurf (Codeium) ---
        if self.config.windsurfrules and self._write(".windsurfrules", HEADER + POINTER):
            written.append(".windsurfrules")

        # --- Cline (VS Code extension) ---
        if self.config.clinerules and self._write(".clinerules", HEADER + POINTER):
            written.append(".clinerules")

        # --- Zed AI ---
        if self.config.zed_rules and self._write(".rules", HEADER + POINTER):
            written.append(".rules")

        # --- Aider ---
        if self.config.aider_conventions and self._write(
            "CONVENTIONS.md",
            HEADER + "\nSee [AGENTS.md](./AGENTS.md) for full project governance guidelines.\n",
        ):
            written.append("CONVENTIONS.md")

        # --- Claude Code (Anthropic) ---
        if self.config.claude_md and self._write_claude_md():
            written.append("CLAUDE.md")

        # --- GitHub Copilot ---
        if self.config.copilot_instructions and self._write_github_file(
            ".github/copilot-instructions.md",
            HEADER + "\nSee [AGENTS.md](./AGENTS.md) for full project governance rules.\n",
        ):
            written.append(".github/copilot-instructions.md")

        # --- Amazon Q Developer ---
        if self.config.amazonq_rules and self._write_github_file(
            ".amazonq/rules/project-rules.md",
            HEADER + "\nSee [AGENTS.md](./AGENTS.md) for full project governance rules.\n",
        ):
            written.append(".amazonq/rules/project-rules.md")

        # --- Continue.dev ---
        if self.config.continue_rules and self._write_github_file(
            ".continue/rules.md",
            HEADER + "\nSee [AGENTS.md](./AGENTS.md) for full project governance rules.\n",
        ):
            written.append(".continue/rules.md")

        return written

    # ------------------------------------------------------------------ helpers

    def _is_managed(self, target: Path, content: str) -> bool:
        """True when it is safe to write: file is missing, identical, or already ours."""
        if not target.exists():
            return True
        try:
            existing = target.read_text(encoding="utf-8")
        except Exception:
            return False
        if existing == content:
            return False  # already up-to-date — nothing to write
        return SIGNATURE in existing

    def _write(self, relative_path: str, content: str) -> bool:
        target = self.workspace_path / relative_path
        if not self._is_managed(target, content):
            return False
        target.write_text(content, encoding="utf-8")
        return True

    def _write_github_file(self, relative_path: str, content: str) -> bool:
        target = self.workspace_path / relative_path
        if not self._is_managed(target, content):
            return False
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return True

    def _write_claude_md(self) -> bool:
        tc = "\n".join([f"- `{c}`" for c in self.profile.test_commands])
        bc = "\n".join([f"- `{c}`" for c in self.profile.build_commands])
        commands: list[str] = []
        if bc:
            commands.append("### Build\n" + bc)
        if tc:
            commands.append("### Test\n" + tc)
        cmds_str = "\n\n".join(commands) if commands else "None detected."

        # Claude Code natively imports other memory files via `@path` references,
        # so we reference AGENTS.md directly instead of relying on a markdown link.
        content = f"""# Project Context

{HEADER}@AGENTS.md

## Quick Commands

{cmds_str}
"""
        return self._write("CLAUDE.md", content)
