from pathlib import Path
from core.config import OutputConfig
from core.analyzer import ProjectProfile


HEADER = "# Auto-generated by ai-context-generator — do not edit directly.\n# See AGENTS.md for the master project governance guidelines.\n"


class BridgeWriter:
    """Generates lightweight pointer files so every AI tool reads from the same AGENTS.md."""

    def __init__(self, workspace_path: Path, config: OutputConfig, profile: ProjectProfile):
        self.workspace_path = workspace_path
        self.config = config
        self.profile = profile

    def write_all(self) -> list[str]:
        written: list[str] = []

        # --- Cursor IDE ---
        if self.config.cursorrules:
            self._write(
                ".cursorrules",
                f"{HEADER}@import ./AGENTS.md\n",
            )
            written.append(".cursorrules")

        # --- Windsurf (Codeium) ---
        if self.config.windsurfrules:
            self._write(
                ".windsurfrules",
                f"{HEADER}@import ./AGENTS.md\n",
            )
            written.append(".windsurfrules")

        # --- Cline (VS Code extension) ---
        if self.config.clinerules:
            self._write(
                ".clinerules",
                f"{HEADER}@import ./AGENTS.md\n",
            )
            written.append(".clinerules")

        # --- Zed AI ---
        if self.config.zed_rules:
            self._write(
                ".rules",
                f"{HEADER}@import ./AGENTS.md\n",
            )
            written.append(".rules")

        # --- Aider ---
        if self.config.aider_conventions:
            self._write(
                "CONVENTIONS.md",
                f"{HEADER}\nSee [AGENTS.md](./AGENTS.md) for full project governance guidelines.\n",
            )
            written.append("CONVENTIONS.md")

        # --- Claude Code (Anthropic) ---
        if self.config.claude_md:
            self._write_claude_md()
            written.append("CLAUDE.md")

        # --- GitHub Copilot ---
        if self.config.copilot_instructions:
            self._write_github_file(
                ".github/copilot-instructions.md",
                f"{HEADER}\nSee [AGENTS.md](./AGENTS.md) for full project governance rules.\n",
            )
            written.append(".github/copilot-instructions.md")

        # --- Amazon Q Developer ---
        if self.config.amazonq_rules:
            self._write_github_file(
                ".amazonq/rules/project-rules.md",
                f"{HEADER}\nSee [AGENTS.md](./AGENTS.md) for full project governance rules.\n",
            )
            written.append(".amazonq/rules/project-rules.md")

        # --- Continue.dev ---
        if self.config.continue_rules:
            self._write_github_file(
                ".continue/rules.md",
                f"{HEADER}\nSee [AGENTS.md](./AGENTS.md) for full project governance rules.\n",
            )
            written.append(".continue/rules.md")

        return written

    # ------------------------------------------------------------------ helpers

    def _write(self, relative_path: str, content: str) -> None:
        target = self.workspace_path / relative_path
        target.write_text(content, encoding="utf-8")

    def _write_github_file(self, relative_path: str, content: str) -> None:
        target = self.workspace_path / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    def _write_claude_md(self) -> None:
        tc = "\n".join([f"- `{c}`" for c in self.profile.test_commands])
        bc = "\n".join([f"- `{c}`" for c in self.profile.build_commands])
        commands: list[str] = []
        if bc:
            commands.append("### Build\n" + bc)
        if tc:
            commands.append("### Test\n" + tc)
        cmds_str = "\n\n".join(commands) if commands else "None detected."

        content = f"""# Project Context

{HEADER}
Refer to [AGENTS.md](./AGENTS.md) for full governance guidelines.

## Quick Commands

{cmds_str}
"""
        (self.workspace_path / "CLAUDE.md").write_text(content, encoding="utf-8")
