from pathlib import Path
from core.config import OutputConfig
from core.analyzer import ProjectProfile

class BridgeWriter:
    def __init__(self, workspace_path: Path, config: OutputConfig, profile: ProjectProfile):
        self.workspace_path = workspace_path
        self.config = config
        self.profile = profile

    def write_all(self) -> list[str]:
        written = []
        if self.config.cursorrules:
            self._write_cursorrules()
            written.append(".cursorrules")
            
        if self.config.claude_md:
            self._write_claude_md()
            written.append("CLAUDE.md")
            
        if self.config.copilot_instructions:
            self._write_copilot_instructions()
            written.append(".github/copilot-instructions.md")
            
        return written

    def _write_cursorrules(self):
        content = """# Auto-generated by ai-context-generator — do not edit directly
# See AGENTS.md for the master project governance guidelines
@import ./AGENTS.md
"""
        (self.workspace_path / ".cursorrules").write_text(content, encoding="utf-8")

    def _write_claude_md(self):
        tc = "\n".join([f"- `{c}`" for c in self.profile.test_commands])
        bc = "\n".join([f"- `{c}`" for c in self.profile.build_commands])
        commands = []
        if bc:
            commands.append("Build commands:\n" + bc)
        if tc:
            commands.append("Test commands:\n" + tc)
        
        cmds_str = "\n\n".join(commands) if commands else "None detected."
        
        content = f"""# Project Context

This file is auto-generated by ai-context-generator.
Refer to [AGENTS.md](./AGENTS.md) for full governance guidelines.

## Quick Commands
{cmds_str}
"""
        (self.workspace_path / "CLAUDE.md").write_text(content, encoding="utf-8")

    def _write_copilot_instructions(self):
        github_dir = self.workspace_path / ".github"
        github_dir.mkdir(exist_ok=True)
        content = """# GitHub Copilot Instructions

This file is auto-generated by ai-context-generator.
Refer to [AGENTS.md](./AGENTS.md) for full project governance rules.
"""
        (github_dir / "copilot-instructions.md").write_text(content, encoding="utf-8")
