from pathlib import Path

from ai_context_generator.analyzer import ProjectProfile
from ai_context_generator.config import OutputConfig

HEADER = "# Auto-generated by ai-context-generator — do not edit directly.\n# See AGENTS.md for the master project governance guidelines.\n"
SIGNATURE = "Auto-generated by ai-context-generator"

POINTER = (
    "This file is auto-generated and lightweight.\n"
    "Read AGENTS.md (in the repository root) for the full project governance guidelines.\n"
    "When AGENTS.md changes, re-run ai-context-generator to refresh this file.\n"
)

_MARKDOWN_POINTER = (
    HEADER + "\nSee [AGENTS.md](./AGENTS.md) for full project governance guidelines.\n"
)


class BridgeWriter:
    """Generates lightweight pointer files so every AI tool reads from the same AGENTS.md.

    A bridge file is only written when it is missing or was previously written by
    this tool (identified by ``SIGNATURE``). Hand-written files are never
    clobbered — they are reported through :attr:`skipped` instead.
    """

    def __init__(self, workspace_path: Path, config: OutputConfig, profile: ProjectProfile):
        self.workspace_path = workspace_path
        self.config = config
        self.profile = profile
        self.skipped: list[str] = []

    def write_all(self) -> list[str]:
        written: list[str] = []
        self.skipped = []

        # (config flag, relative path, content) — CLAUDE.md is built separately
        # because it embeds the detected build/test commands.
        plain_bridges: list[tuple[bool, str, str]] = [
            (self.config.cursorrules, ".cursorrules", HEADER + POINTER),
            (self.config.windsurfrules, ".windsurfrules", HEADER + POINTER),
            (self.config.clinerules, ".clinerules", HEADER + POINTER),
            (self.config.zed_rules, ".rules", HEADER + POINTER),
            (self.config.aider_conventions, "CONVENTIONS.md", _MARKDOWN_POINTER),
            (
                self.config.copilot_instructions,
                ".github/copilot-instructions.md",
                _MARKDOWN_POINTER,
            ),
            (self.config.amazonq_rules, ".amazonq/rules/project-rules.md", _MARKDOWN_POINTER),
            (self.config.continue_rules, ".continue/rules.md", _MARKDOWN_POINTER),
        ]

        for enabled, relative_path, content in plain_bridges:
            if enabled and self._write(relative_path, content):
                written.append(relative_path)

        if self.config.claude_md and self._write("CLAUDE.md", self._claude_md_content()):
            written.append("CLAUDE.md")

        return written

    # ------------------------------------------------------------------ helpers

    def _is_managed(self, target: Path, content: str) -> bool:
        """True when it is safe to write: file is missing, identical, or already ours."""
        if not target.exists():
            return True
        try:
            existing = target.read_text(encoding="utf-8")
        except OSError:
            return False
        if existing == content:
            return False  # already up-to-date — nothing to write
        return SIGNATURE in existing

    def _write(self, relative_path: str, content: str) -> bool:
        target = self.workspace_path / relative_path
        if not self._is_managed(target, content):
            # Distinguish "identical, nothing to do" from "user owns this file".
            if target.exists():
                try:
                    if SIGNATURE not in target.read_text(encoding="utf-8"):
                        self.skipped.append(relative_path)
                except OSError:
                    self.skipped.append(relative_path)
            return False
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return True

    def _claude_md_content(self) -> str:
        tc = "\n".join(f"- `{c}`" for c in self.profile.test_commands)
        bc = "\n".join(f"- `{c}`" for c in self.profile.build_commands)
        commands: list[str] = []
        if bc:
            commands.append("### Build\n" + bc)
        if tc:
            commands.append("### Test\n" + tc)
        cmds_str = "\n\n".join(commands) if commands else "None detected."

        # Claude Code natively imports other memory files via `@path` references,
        # so we reference AGENTS.md directly instead of relying on a markdown link.
        return f"""# Project Context

{HEADER}@AGENTS.md

## Quick Commands

{cmds_str}
"""
